### ISSUE TITLE
pathFinding() is not triggered

### ISSUE THREAD

**Issue by ZhangzrJerry** [Jason-xy/elec3210-lab#4]
`pathFinding()` in `demo_node.cpp` is called by `rcvWaypointsCallback()`, which is trigged by `rostopic /waypoint_generator/waypoints`

```bash
# rostopic info /waypoint_generator/waypoints
Type: nav_msgs/Path

Publishers: 
 * /waypoint_generator (http://b1dc80ea0e86:42761/)

Subscribers: 
 * /demo_node (http://b1dc80ea0e86:39391/)

# rostopic hz /waypoint_generator/waypoints
subscribed to [/waypoint_generator/waypoints]

no new messages
```
While `/waypoint_generator/waypoints` is published by `pub1` in `waypoint_generator.cpp`. `pub1.publish(waypoints)` is called by `publish_waypoints()`. And `publish_waypoints()` is called by `odom_callback()`, `goal_callback()` or `traj_start_trigger_callback()`.

And
```cpp
ros::NodeHandle n("~");
n.param("waypoint_type", waypoint_type, string("manual"));
ros::Subscriber sub1 = n.subscribe("odom", 10, odom_callback);
ros::Subscriber sub2 = n.subscribe("goal", 10, goal_callback);
ros::Subscriber sub3 =
    n.subscribe("traj_start_trigger", 10, traj_start_trigger_callback);
```

But
```bash
# rostopic info /waypoint_generator/odom
Type: nav_msgs/Odometry

Publishers: None

Subscribers: 
 * /waypoint_generator (http://b1dc80ea0e86:40199/)

# rostopic info /waypoint_generator/traj_start_trigger
Type: geometry_msgs/PoseStamped

Publishers: None

Subscribers: 
 * /waypoint_generator (http://b1dc80ea0e86:40199/)

# rostopic info /goal
Type: geometry_msgs/PoseStamped

Publishers: 
 * /rviz (http://b1dc80ea0e86:45301/)

Subscribers: 
 * /waypoint_generator (http://b1dc80ea0e86:40199/)

# rostopic hz /goal
subscribed to [/goal]
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
```

Although `/goal` is registered from `goal_tool.cpp` but `Goal3Dtool::updateTopic()` is always not called.

So `pathFinding()` cannot be triggered. I have no idea how to figure it out.

**Comment by Jason-xy** [comment]
Did you click the `3D Nav Goal` button in the rviz toolbar, then click and drag on the map to set the goal point?
![](https://wpcos-1300629776.cos.ap-chengdu.myqcloud.com/wpcos-1300629776/Gallery20240828200134.png)

**Comment by ZhangzrJerry** [comment]
No, I didn't T_T )embarrased

**Comment by ZhangzrJerry** [comment]
Thank you so much
